name: flight_tracker
description: An app to check the status of flights
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  
  intl: any
  #manage state
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  equatable: ^2.0.5
  #call api
  http: ^1.1.0
  #save data
  shared_preferences: ^2.2.0
  sqflite: ^2.2.8+4
  #icon
  font_awesome_flutter: ^10.5.0
  cupertino_icons: ^1.0.2
  #resize text
  auto_size_text: ^3.0.0
  # manage image
  flutter_svg: ^2.0.7
  # manage routing
  auto_route: ^8.1.3
  #onboarding and splash
  smooth_page_indicator: ^1.1.0
  flutter_native_splash: ^2.3.1
  #help print log 
  logger: ^2.0.1
  flutter_localizations:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter 
  flutter_lints: ^4.0.0                 
  auto_route_generator: ^8.0.0               
  build_runner:       
  

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
    - assets/json/
    - assets/img/

  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-Regular.ttf
        - asset: assets/fonts/RobotoMono-Light.ttf
        - asset: assets/fonts/RobotoMono-Medium.ttf
        - asset: assets/fonts/RobotoMono-Bold.ttf
          weight: 700
 
flutter_native_splash:
  color: "#1565C0"
  image: assets/img/logo.png
  branding_mode: bottomRight
  web: false
